//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Стомотология.БД
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ПоликлиникаEntities3 : DbContext
    {
        private static ПоликлиникаEntities3 _context;

        public ПоликлиникаEntities3()
            : base("name=ПоликлиникаEntities3")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public static ПоликлиникаEntities3 GetContext()
        {
            if (_context == null)
            {
                _context = new ПоликлиникаEntities3();
            }
            return _context;
        }

        public virtual DbSet<Врач> Врач { get; set; }
        public virtual DbSet<Диагноз> Диагноз { get; set; }
        public virtual DbSet<Пациент> Пациент { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<Прием> Прием { get; set; }
        public virtual DbSet<Талон> Талон { get; set; }
        public virtual DbSet<Услуги> Услуги { get; set; }
    }
}
